image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
    - build
    - package
    - deploy

maven-build:
  image: maven:alpine
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar






