image: maven:alpine

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'

default:
  tags:
    - docker
  
variables:
  SPRING_PROFILES_ACTIVE: dev
  IMAGE_NAME: crisphung/itss-be
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  IMAGE_TAG: v1

cache:
  paths:
    - ".m2/repository"

stages:
    - build
    - docker
    - deploy

maven-build:
  stage: build
  before_script:
    - mvn --version
  script: 
    - echo "Start build package"
    - mvn package -B
    - echo "Build finish!"
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

docker-job:
  stage: docker
  image: docker:20.10.22
  services:
    - docker:20.10.22-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy-job:
  stage: deploy
  script:
    - echo "Deploying..."
  







