image: docker:latest
services:
  - docker:dind


variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  IMAGE_NAME: crisphung/itss-be

stages:
    - build
    - package
    - deploy

maven-build:
  stage: build
  before_script:
    - docker login -u $DOCKER_USER -p DOCKER_PASSWORD
  script: 
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  







