spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  main:
    allow-circular-references: true

jwt:
  secretKey: quanify
  expirationDateInMs: 3000000
  refreshExpirationDateInMs: 9000000